config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :microposts
  root 'microposts#index'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :recoverable, :timeoutable, :lockable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable, :trackable
  has_many :microposts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :micropost
  validates_presence_of :url
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :account
  has_one :card, dependent: :destroy

  accepts_nested_attributes_for :card, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :authenticate_account!
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  skip_before_action :authenticate_account!, only: [:index, :show]
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @pagy, @microposts = pagy(Micropost.includes(:account).order(id: :desc))
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = current_account.microposts.build
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_account.microposts.build(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to :root, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:body, card_attributes: [:url])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
  LINK_REL = 'nofollow noopener noreferrer'

  def sanitize_and_replace_to_link(body)
    sanitize(strip_links(body).gsub(%r{(https?://[^\s]+)}) do |link|
      text = truncate(link.sub(%r{https?://}, ''))
      link_to(text, link, rel: LINK_REL, target: '_blank')
    end, tags: %w[a], attributes: %w[href rel target])
  end
end

app/views/bootstrap/_alerts.html.erb
<%= content_tag(:div, notice, class: 'alert alert-primary', role: 'alert') if notice %>

app/views/bootstrap/_footer.html.erb
<hr class="my-5" />

<footer class="pb-5">
  <p class="my-0 float-right"><a href="#">Back to top</a></p>
  <p class="my-0">
    Source code available at
    <a href="https://github.com/nzwsch/micro">GitHub</a>
  </p>
</footer>

app/views/bootstrap/_navbar.html.erb
<nav class="navbar navbar-light mb-4" style="background-color: #e3f2fd;">
  <div class="container">
    <%= link_to "Micro", root_path, class: 'navbar-brand mb-0 h1' %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if account_signed_in? %>
          <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to "Sign in", new_account_session_path, class: 'nav-link' %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Micro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'bootstrap' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'bootstrap/navbar' %>
    <div class="container">
      <%= render 'bootstrap/alerts' %>
      <%= yield %>
      <%= render 'bootstrap/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="media pt-2 border-bottom">
  <div class="mb-2 mr-3">
    <%= image_tag micropost.account.avatar_url, alt: micropost.account.name, size: '64x64' %>
  </div>
  <div class="media-body">
    <%= content_tag :p, class: 'mb-2' do %>
      <%= content_tag :strong, micropost.account.name, class: 'mr-2 text-primary' %>
      <%= sanitize_and_replace_to_link micropost.body %>
    <% end %>
    <ul class="nav micropost-actions">
      <li class="nav-item"><%= link_to "#{distance_of_time_in_words_to_now(micropost.created_at)} ago", micropost, class: 'nav-link' %></li>
      <% if account_signed_in? %>
        <li class="nav-item"><%= link_to 'Edit', edit_micropost_path(micropost), class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<%= content_tag :div, '', id: 'shout_out' if account_signed_in? %>

<h3 class="my-3 text-primary">Shouts</h3>

<% @microposts.each do |micropost| %>
  <% cache_unless account_signed_in?, micropost do %>
    <%= render "micropost", micropost: micropost %>
  <% end %>
<% end %>

<br />

<%== pagy_nav_bootstrap(@pagy) %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @micropost.account.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= sanitize @micropost.body %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) if account_signed_in? %>
<%= link_to 'Back', microposts_path %>